### ISSUE TITLE
Make sure each navigable page has a lead paragraph

### ISSUE THREAD

**Issue by ericearl** [bids-standard/bids-website#461] opened 2024-07-29 14:58 UTC
### Your idea

As suggested by @robertoostenveld in a Slack thread, I think it would be good to start each major page (when someone clicks on a navigation "tab") with a lead paragraph. See a nice Wikipedia outline here for more details:

https://en.wikipedia.org/wiki/Lead_paragraph

**Comment by Remi-Gau** [comment] 2024-09-12 16:28
possible duplicate of #485

**Comment by Remi-Gau** [comment] 2024-09-13 16:18
- I think that in essence #447 is also the same as this one.

**Comment by Remi-Gau** [comment] 2024-09-16 08:35
Related:

The landing page of the tool section should have brief description of the different sub sections when can find in it.

Very confusing for people on mobile who otherwise have to open the navbar to discover the content.

_Originally posted by @Remi-Gau in https://github.com/bids-standard/bids-website/discussions/407#discussioncomment-9911851_

**Comment by bendhouseart** [comment] 2024-09-19 01:14
Closed with pr #498

**Closed by bendhouseart** 2024-09-19 01:14 UTC
Labels: enhancement, dvd, priority: medium
