### ISSUE TITLE
Make the impact page tell the story of BIDS' impact

### ISSUE THREAD

**Issue by ericearl** [bids-standard/bids-website#486] opened 2024-09-09 12:18 UTC
Take a first pass at improving the Impact page to be more about the Impact of BIDS. Even if this means just moving the current content around and re-using the last BIDS town hall slide content.

from #481 

Reorganize the [impact page](https://bids-website.readthedocs.io/en/latest/impact/index.html):

- [x] Reorder content to show metrics, history, deliverables, and place how to cite etc etc at the very end/bottom of page
- [x] Integrate slides from OHBM into impact page, no reason not to use existing work.
- [x] Add/update paragraphs/statements for existing content? @iamdamion @ericearl  update this item.

**Comment by Remi-Gau** [comment] 2024-09-13 16:38
duplicate of #481

**Comment by christinerogers** [comment] 2024-09-19 16:18
target -- first draft for: Sep. 26
Bring questions to check-in : Sep.26

**Comment by christinerogers** [comment] 2024-10-17 16:36
Damion - looking for a PR /commit next week.  
This is still priority.  

Additional content for reference: https://pmc.ncbi.nlm.nih.gov/articles/PMC10516110/

**Closed** 2024-12-05 17:05 UTC
Labels: dvd
